[package]
name = "stash"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.4.10"
rand = "0.8.5"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["serve"]
